os:
  - linux
services:
  - docker
before_install:
  - wget -qO- https://get.docker.com/ | sh
  - docker version
install:
  - docker build -t jhipster/jhipster-registry:travis .
  - docker images
  - docker run --name jhipster-registry -p 8761:8761 -d -t jhipster/jhipster-registry:travis
script:
  - sleep 45
  - docker ps
  - docker logs jhipster-registry
  - curl -v http://localhost:8761
