spring:
    security:
        oauth2:
            client:
                provider:
                 oidc:
                     issuer-uri: http://localhost:9080/auth/realms/jhipster
                registration:
                    oidc:
                       client-id: web_app
                       client-secret: web_app

server:
    servlet:
        session:
            cookie:
                http-only: true
                # custom session cookie name to prevent conflict with another application on the same domain
                name: JSESSIONID_REGISTRY
