version: '2'
services:
    jhipsterregistry-app:
        image: jhipsterregistry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
